spring:
  profiles:
    active: local

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service?useSSL=false&useTimezone=true&serverTimezone=UTC
    username: HBB001
    password: HBB001
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      transaction-isolation: TRANSACTION_READ_COMMITTED
      pool-name: pool-board-service

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update

jwt:
  header: Authorization
  secret: 842f516824165bcde7ec45ed4548101e38e77bd5e6e674e68f406dd8f1e8034ffe637e81274717f5463736faf1bcd8d68d7145c828046cddfeca94264c400423
  access-token-validity-in-seconds: 600

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE